name: Update AltStore Repo

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

concurrency:
  group: update-altstore-repo
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Build and update source.json
        run: uv run scripts/update_source.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add source.json
          latest_version=$(jq -r '.apps[0].versions[0].version // "unknown"' source.json)
          echo latest version is $latest_version
          
          if git diff --cached --quiet; then
            echo "No changes in source.json"
            exit 0
          fi


          git commit -m "chore: update PiliPlus AltStore repo (${latest_version})"
          git push

